"""Conformance runner: every corpus case must produce byte-identical canonical output.

Cases are discovered from corpus/MANIFEST.json (generated by corpus/tools/gen_all.py).
Each case asserts, per ADR-0001:
  1. input.fit matches its recorded sha256 (hand-edit guard)
  2. lenient-mode canonical output == expected.json, byte for byte
  3. the lenient grade (ok | partial | reject) holds
  4. strict-mode expectation holds (raise:<CODE> or no raise)
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import pytest

REPO = Path(__file__).resolve().parents[3]
CORPUS = REPO / "corpus"


def _load_cases() -> list[tuple[str, Path, dict[str, Any]]]:
    out = []
    for manifest, base in (
        (CORPUS / "MANIFEST.json", CORPUS),
        (CORPUS / "private" / "MANIFEST.json", CORPUS / "private"),  # ADR-0007 tier
    ):
        if not manifest.exists():
            continue
        for rel in json.loads(manifest.read_text())["cases"]:
            case_dir = base / rel
            if not (case_dir / "input.fit").exists():
                continue  # private cases exist only on some machines
            case = json.loads((case_dir / "case.json").read_text())
            tag = rel if base is CORPUS else f"private/{rel}"
            out.append((tag, case_dir, case))
    return out


CASES = _load_cases()


def _check_grade(result: Any, grade: str, rel: str) -> None:
    if grade == "ok":
        assert result.ok, f"{rel}: expected ok, got errors={result.errors}"
        assert not result.errors, f"{rel}: expected clean, got errors={result.errors}"
    elif grade == "partial":
        assert result.ok, f"{rel}: expected usable (partial) output"
        assert result.recovery is not None or result.errors, (
            f"{rel}: 'partial' requires recovery engagement or collected errors"
        )
    elif grade == "reject":
        assert not result.ok, f"{rel}: expected reject, got ok"
        assert result.errors, f"{rel}: reject must carry a typed error"
    else:  # pragma: no cover - corpus authoring error
        pytest.fail(f"{rel}: unknown grade {grade!r}")


@pytest.mark.parametrize(("rel", "case_dir", "case"), CASES, ids=[c[0] for c in CASES])
def test_corpus_case(rel: str, case_dir: Path, case: dict[str, Any]) -> None:
    import chiptime
    from chiptime.errors import FitError

    data = (case_dir / "input.fit").read_bytes()
    assert hashlib.sha256(data).hexdigest() == case["input_sha256"], (
        f"{rel}: input.fit was modified outside gen_all.py"
    )

    # lenient: canonical snapshot + grade
    result = chiptime.parse(data, mode="lenient")
    expected = case_dir / "expected.json"
    assert expected.exists(), f"{rel}: expected.json missing — run gen_all.py --expected"
    assert result.to_canonical_json() == expected.read_bytes(), (
        f"{rel}: canonical output diverged from snapshot"
    )
    _check_grade(result, case["modes"]["lenient"], rel)

    # determinism: a second parse must be byte-identical
    assert chiptime.parse(data, mode="lenient").to_canonical_json() == expected.read_bytes()

    # strict
    strict_exp = case["modes"]["strict"]
    if strict_exp == "unchecked":
        return  # real files (ADR-0007): strict outcome varies by device honesty
    if strict_exp.startswith("raise:"):
        with pytest.raises(FitError) as ei:
            chiptime.parse(data, mode="strict")
        assert ei.value.code == strict_exp.removeprefix("raise:"), rel
    else:
        strict_result = chiptime.parse(data, mode="strict")
        _check_grade(strict_result, strict_exp, rel)

    # forensic must never raise and must be deterministic too
    forensic = chiptime.parse(data, mode="forensic")
    _check_grade(forensic, case["modes"]["forensic"], rel)
    assert chiptime.parse(data, mode="forensic").to_canonical_json() == forensic.to_canonical_json()
