#!/usr/bin/env python3
"""Generate docs/for-agents.md from the code registries (single source of truth).

Run from repo root:  uv run --project python python scripts/gen_agent_docs.py
Re-run whenever errors.py registries change; /verify checks freshness.
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "python" / "src"))

from chiptime.errors import ERROR_CODES, PROVENANCE_CODES, WARNING_CODES  # isort:skip
from chiptime.metrics import INSIGHT_CODES  # isort:skip  (optional layer; script-only import)


def table(d: dict[str, str]) -> str:
    lines = ["| Code | Meaning |", "|---|---|"]
    lines += [f"| `{k}` | {v} |" for k, v in d.items()]
    return "\n".join(lines)


DOC = f"""# chiptime for agents

> Generated by `scripts/gen_agent_docs.py` from the code registries — do not hand-edit.

chiptime is built to be consumed by automation: deterministic output, stable machine codes,
and exit codes that tell you what to do next.

## Quickstart

```python
import chiptime

result = chiptime.parse("activity.fit")        # lenient: recover + annotate (default)
result.ok                                      # usable output produced?
result.file_type                               # "activity" | "course" | "workout" | ...
result.activity.sessions[0].records.stream("power")  # values: 0 is real, None is absent
result.recovery                                # None unless salvage/resync engaged
result.provenance                              # every drop/repair/synthesis, typed
result.to_canonical_json()                     # RFC 8785 bytes — byte-identical every run
```

Modes: `strict` raises the first defect (spec-lawyer) · `lenient` recovers and records ·
`forensic` detects like lenient but never drops values (annotates instead).

## CLI exit codes (stable contract)

| Code | Meaning | Agent action |
|---|---|---|
| 0 | Parsed clean (warnings possible) | Consume the output |
| 2 | Parsed with recovery/data loss | Consume; inspect `provenance[]` + `recovery` |
| 3 | Unusable input | Inspect `errors[]`; nothing salvageable |
| 4 | Not a FIT file | Route to the parser the error names |
| 64 | Usage error | Fix the invocation |

`chiptime parse FILE --json` emits canonical JSON on stdout; `chiptime codes` prints this
registry; `chiptime inspect FILE` shows the wire-level frame table.

## Canonical output shape (schema `chiptime_schema: 1`)

Top level: `ok · mode · source(sha256,size_bytes,unwrapped) · parts[] · errors[] ·
warnings[] · provenance[] · recovery`. Each activity part carries `activity` with
`sessions[]` (declared vs derived totals + discrepancies, laps, lengths, records as
**columnar streams**), `events[]`, `gaps[]` (classified), `device`, `athlete`,
`utc_offset_s`. Record messages fold into streams losslessly — every record field,
known or unknown, becomes a stream column; in streams `null` means *absent* and `0`
means *zero* — never conflate them. Integers beyond 2^53-1 are decimal strings.
The local file path is never serialized.

## Error codes (`errors[]`, raised in strict)

{table(ERROR_CODES)}

## Warning codes (`warnings[]` — seen and continued)

{table(WARNING_CODES)}

## Provenance codes (`provenance[]` — what chiptime did)

{table(PROVENANCE_CODES)}

Every provenance entry carries `action` (`dropped | repaired | synthesized |
reinterpreted | ignored`), a scope, a human sentence, and machine `data`.

## Insight codes (`chiptime analyze` / `chiptime.metrics.analyze`)

The optional analytics layer (ADR-0008) reports per-session workout analysis.
`chiptime analyze FILE --json` emits a deterministic report; insights carry a
stable CODE, a human sentence, and numeric `evidence`. Derived numbers carry a
`basis` string (e.g. `power+ftp`, `hr-trimp`, `laps:manual`,
`detected:power-steps`) and analyses whose inputs are absent land in
`omissions[]` with a reason — thresholds are never estimated from the workout.

{table(INSIGHT_CODES)}
"""

out = pathlib.Path(__file__).resolve().parents[1] / "docs" / "for-agents.md"
out.write_text(DOC)
print(f"wrote {out} ({len(DOC)} chars)")
