"""chiptime.metrics — optional analytics on chiptime's honest streams.

Import explicitly (`from chiptime import metrics`); the core never imports
this package (test-enforced). Everything inherits the streams' guarantees:
sentinels are already null, zero is real (taxonomy #64). Names are generic
on purpose — no trademarked training-metric names (ADR-0008 §7).
"""

from chiptime.metrics._basics import (
    MEAN_MAX_MIN_COVERAGE,
    ZONE_DT_CAP_S,
    mean_max,
    swolf,
    time_in_zones,
)
from chiptime.metrics.insights import (
    COASTING_SHARE_PCT,
    HR_DRIFT_PCT,
    INSIGHT_CODES,
    SPLIT_DELTA_PCT,
    ActivityReport,
    Insight,
    WorkoutReport,
    analyze,
    analyze_session,
)
from chiptime.metrics.intervals import (
    MAX_DURATION_CV,
    MIN_WORK_REPS,
    RECOVERY_BAND,
    SWIM_SET_REST_MIN_S,
    WORK_BAND,
    Interval,
    IntervalStructure,
    RepeatGroup,
    detect_structure,
)
from chiptime.metrics.load import (
    FATIGUE_TC_DAYS,
    FITNESS_TC_DAYS,
    TRIMP_K_FEMALE,
    TRIMP_K_MALE,
    TRIMP_MIN_COVERAGE,
    WEIGHTED_POWER_WINDOW,
    FitnessPoint,
    LoadEstimate,
    fitness_fatigue_form,
    hr_coverage_fraction,
    intensity_ratio,
    load_score,
    trimp,
    weighted_avg_power,
    work_kj,
    workout_load,
)
from chiptime.metrics.pacing import (
    CONCEPT2_COEFF,
    Split,
    distance_splits,
    format_pace,
    format_speed_kmh,
    pace_seconds,
    session_pace_s,
    speed_from_pace,
    split_500m_to_watts,
    watts_to_split_500m,
)
from chiptime.metrics.settings import AthleteSettings
from chiptime.metrics.sports import (
    RUN_PER_LEG_CADENCE_MAX,
    PaceStyle,
    SportProfile,
    cadence_display,
    primary_signal,
    profile_for,
)
from chiptime.metrics.zones import hr_zone_bounds, power_zone_bounds

__all__ = [
    "COASTING_SHARE_PCT",
    "CONCEPT2_COEFF",
    "FATIGUE_TC_DAYS",
    "FITNESS_TC_DAYS",
    "HR_DRIFT_PCT",
    "INSIGHT_CODES",
    "MAX_DURATION_CV",
    "MEAN_MAX_MIN_COVERAGE",
    "MIN_WORK_REPS",
    "RECOVERY_BAND",
    "RUN_PER_LEG_CADENCE_MAX",
    "SPLIT_DELTA_PCT",
    "SWIM_SET_REST_MIN_S",
    "TRIMP_K_FEMALE",
    "TRIMP_K_MALE",
    "TRIMP_MIN_COVERAGE",
    "WEIGHTED_POWER_WINDOW",
    "WORK_BAND",
    "ZONE_DT_CAP_S",
    "ActivityReport",
    "AthleteSettings",
    "FitnessPoint",
    "Insight",
    "Interval",
    "IntervalStructure",
    "LoadEstimate",
    "PaceStyle",
    "RepeatGroup",
    "Split",
    "SportProfile",
    "WorkoutReport",
    "analyze",
    "analyze_session",
    "cadence_display",
    "detect_structure",
    "distance_splits",
    "fitness_fatigue_form",
    "format_pace",
    "format_speed_kmh",
    "hr_coverage_fraction",
    "hr_zone_bounds",
    "intensity_ratio",
    "load_score",
    "mean_max",
    "pace_seconds",
    "power_zone_bounds",
    "primary_signal",
    "profile_for",
    "session_pace_s",
    "speed_from_pace",
    "split_500m_to_watts",
    "swolf",
    "time_in_zones",
    "trimp",
    "watts_to_split_500m",
    "weighted_avg_power",
    "work_kj",
    "workout_load",
]
